// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace NonAsciiValues
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// NonAsciiValue - Use 'NonAsciiValueParams' to pass parameters into this method.
        /// </summary>
        public void NonAsciiValue()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Click text box
            Mouse.Click(uIItemEdit, new Point(160, 384));

            // Type 'Alt + {NumPad0}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys, ModifierKeys.Alt);

            // Type 'Alt + {NumPad1}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys1, ModifierKeys.Alt);

            // Type 'Alt + {NumPad4}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys2, ModifierKeys.Alt);

            // Type 'Alt + {NumPad7}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys3, ModifierKeys.Alt);

            // Type 'Alt + {NumPad0}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys4, ModifierKeys.Alt);

            // Type 'Alt + {NumPad2}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys5, ModifierKeys.Alt);

            // Type 'Alt + {NumPad5}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys6, ModifierKeys.Alt);

            // Type 'Alt + {NumPad9}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys7, ModifierKeys.Alt);

            // Type 'Alt + {NumPad9}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys8, ModifierKeys.Alt);

            // Type 'Alt + {NumPad1}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys9, ModifierKeys.Alt);

            // Type 'Alt + {NumPad2}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys10, ModifierKeys.Alt);

            // Type 'Alt + {NumPad3}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys11, ModifierKeys.Alt);

            // Type 'Alt + {NumPad4}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys12, ModifierKeys.Alt);

            // Type 'Alt + {NumPad4}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys13, ModifierKeys.Alt);

            // Type 'Alt + {NumPad5}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys14, ModifierKeys.Alt);

            // Type 'Alt + {NumPad8}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys15, ModifierKeys.Alt);

            // Type 'Alt + {NumPad7}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys16, ModifierKeys.Alt);

            // Type 'Alt + {NumPad4}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys17, ModifierKeys.Alt);

            // Type 'Alt + {NumPad5}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys18, ModifierKeys.Alt);

            // Type 'Alt + {NumPad6}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys19, ModifierKeys.Alt);

            // Type 'Alt + {NumPad3}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys20, ModifierKeys.Alt);

            // Type 'Alt + {NumPad1}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys21, ModifierKeys.Alt);

            // Type 'Alt + {NumPad2}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys22, ModifierKeys.Alt);

            // Type 'Alt + {NumPad3}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys23, ModifierKeys.Alt);

            // Type 'Alt + {NumPad4}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys24, ModifierKeys.Alt);

            // Type 'Alt + {NumPad6}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys25, ModifierKeys.Alt);

            // Type 'Alt + {NumPad5}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys26, ModifierKeys.Alt);

            // Type 'Alt + {NumPad4}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys27, ModifierKeys.Alt);

            // Type 'Alt + {NumPad1}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys28, ModifierKeys.Alt);

            // Type 'Alt + {NumPad1}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys29, ModifierKeys.Alt);

            // Type 'Alt + {NumPad4}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys30, ModifierKeys.Alt);

            // Type 'Alt + {NumPad8}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys31, ModifierKeys.Alt);

            // Type 'Alt + {NumPad5}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys32, ModifierKeys.Alt);

            // Type 'Alt + {NumPad1}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys33, ModifierKeys.Alt);

            // Type 'Alt + {NumPad3}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys34, ModifierKeys.Alt);

            // Type 'Alt + {NumPad6}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys35, ModifierKeys.Alt);

            // Type 'Alt + {NumPad9}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys36, ModifierKeys.Alt);

            // Type 'Alt + {NumPad7}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys37, ModifierKeys.Alt);

            // Type 'Alt + {NumPad1}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys38, ModifierKeys.Alt);

            // Type 'Alt + {NumPad4}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys39, ModifierKeys.Alt);

            // Type 'Alt + {NumPad5}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys40, ModifierKeys.Alt);

            // Type 'Alt + {NumPad8}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys41, ModifierKeys.Alt);

            // Type 'Alt + {NumPad7}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys42, ModifierKeys.Alt);

            // Type 'Alt + {NumPad1}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys43, ModifierKeys.Alt);

            // Type 'Alt + {NumPad1}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys44, ModifierKeys.Alt);

            // Type 'Alt + {NumPad1}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys45, ModifierKeys.Alt);

            // Type 'Alt + {NumPad1}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys46, ModifierKeys.Alt);

            // Type 'Alt + {NumPad1}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys47, ModifierKeys.Alt);

            // Type 'Alt + {NumPad2}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys48, ModifierKeys.Alt);

            // Type 'Alt + {NumPad2}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys49, ModifierKeys.Alt);

            // Type 'Alt + {NumPad5}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys50, ModifierKeys.Alt);

            // Type 'Alt + {NumPad4}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys51, ModifierKeys.Alt);

            // Type 'Alt + {NumPad8}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys52, ModifierKeys.Alt);

            // Type 'Alt + {NumPad1}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys53, ModifierKeys.Alt);

            // Type 'Alt + {NumPad4}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys54, ModifierKeys.Alt);

            // Type 'Alt + {NumPad5}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys55, ModifierKeys.Alt);

            // Type 'Alt + {NumPad6}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys56, ModifierKeys.Alt);

            // Type 'Alt + {NumPad3}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys57, ModifierKeys.Alt);

            // Type 'Alt + {NumPad2}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys58, ModifierKeys.Alt);

            // Type 'Alt + {NumPad1}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys59, ModifierKeys.Alt);

            // Type 'Alt + {NumPad4}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys60, ModifierKeys.Alt);

            // Type 'Alt + {NumPad5}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys61, ModifierKeys.Alt);

            // Type 'Alt + {NumPad2}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys62, ModifierKeys.Alt);

            // Type 'Alt + {NumPad0}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys63, ModifierKeys.Alt);

            // Type 'Alt + {NumPad1}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys64, ModifierKeys.Alt);

            // Type 'Alt + {NumPad4}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys65, ModifierKeys.Alt);

            // Type 'Alt + {NumPad5}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys66, ModifierKeys.Alt);

            // Type 'Alt + {NumPad9}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys67, ModifierKeys.Alt);

            // Type 'Alt + {NumPad8}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys68, ModifierKeys.Alt);

            // Type 'Alt + {NumPad7}' in text box
            Keyboard.SendKeys(uIItemEdit, this.NonAsciiValueParams.UIItemEditSendKeys69, ModifierKeys.Alt);
        }
        
        #region Properties
        public virtual NonAsciiValueParams NonAsciiValueParams
        {
            get
            {
                if ((this.mNonAsciiValueParams == null))
                {
                    this.mNonAsciiValueParams = new NonAsciiValueParams();
                }
                return this.mNonAsciiValueParams;
            }
        }
        
        public UIUntitledNotepadWindow UIUntitledNotepadWindow
        {
            get
            {
                if ((this.mUIUntitledNotepadWindow == null))
                {
                    this.mUIUntitledNotepadWindow = new UIUntitledNotepadWindow();
                }
                return this.mUIUntitledNotepadWindow;
            }
        }
        #endregion
        
        #region Fields
        private NonAsciiValueParams mNonAsciiValueParams;
        
        private UIUntitledNotepadWindow mUIUntitledNotepadWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'NonAsciiValue'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class NonAsciiValueParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Alt + {NumPad0}' in text box
        /// </summary>
        public string UIItemEditSendKeys = "{NumPad0}";
        
        /// <summary>
        /// Type 'Alt + {NumPad1}' in text box
        /// </summary>
        public string UIItemEditSendKeys1 = "{NumPad1}";
        
        /// <summary>
        /// Type 'Alt + {NumPad4}' in text box
        /// </summary>
        public string UIItemEditSendKeys2 = "{NumPad4}";
        
        /// <summary>
        /// Type 'Alt + {NumPad7}' in text box
        /// </summary>
        public string UIItemEditSendKeys3 = "{NumPad7}";
        
        /// <summary>
        /// Type 'Alt + {NumPad0}' in text box
        /// </summary>
        public string UIItemEditSendKeys4 = "{NumPad0}";
        
        /// <summary>
        /// Type 'Alt + {NumPad2}' in text box
        /// </summary>
        public string UIItemEditSendKeys5 = "{NumPad2}";
        
        /// <summary>
        /// Type 'Alt + {NumPad5}' in text box
        /// </summary>
        public string UIItemEditSendKeys6 = "{NumPad5}";
        
        /// <summary>
        /// Type 'Alt + {NumPad9}' in text box
        /// </summary>
        public string UIItemEditSendKeys7 = "{NumPad9}";
        
        /// <summary>
        /// Type 'Alt + {NumPad9}' in text box
        /// </summary>
        public string UIItemEditSendKeys8 = "{NumPad9}";
        
        /// <summary>
        /// Type 'Alt + {NumPad1}' in text box
        /// </summary>
        public string UIItemEditSendKeys9 = "{NumPad1}";
        
        /// <summary>
        /// Type 'Alt + {NumPad2}' in text box
        /// </summary>
        public string UIItemEditSendKeys10 = "{NumPad2}";
        
        /// <summary>
        /// Type 'Alt + {NumPad3}' in text box
        /// </summary>
        public string UIItemEditSendKeys11 = "{NumPad3}";
        
        /// <summary>
        /// Type 'Alt + {NumPad4}' in text box
        /// </summary>
        public string UIItemEditSendKeys12 = "{NumPad4}";
        
        /// <summary>
        /// Type 'Alt + {NumPad4}' in text box
        /// </summary>
        public string UIItemEditSendKeys13 = "{NumPad4}";
        
        /// <summary>
        /// Type 'Alt + {NumPad5}' in text box
        /// </summary>
        public string UIItemEditSendKeys14 = "{NumPad5}";
        
        /// <summary>
        /// Type 'Alt + {NumPad8}' in text box
        /// </summary>
        public string UIItemEditSendKeys15 = "{NumPad8}";
        
        /// <summary>
        /// Type 'Alt + {NumPad7}' in text box
        /// </summary>
        public string UIItemEditSendKeys16 = "{NumPad7}";
        
        /// <summary>
        /// Type 'Alt + {NumPad4}' in text box
        /// </summary>
        public string UIItemEditSendKeys17 = "{NumPad4}";
        
        /// <summary>
        /// Type 'Alt + {NumPad5}' in text box
        /// </summary>
        public string UIItemEditSendKeys18 = "{NumPad5}";
        
        /// <summary>
        /// Type 'Alt + {NumPad6}' in text box
        /// </summary>
        public string UIItemEditSendKeys19 = "{NumPad6}";
        
        /// <summary>
        /// Type 'Alt + {NumPad3}' in text box
        /// </summary>
        public string UIItemEditSendKeys20 = "{NumPad3}";
        
        /// <summary>
        /// Type 'Alt + {NumPad1}' in text box
        /// </summary>
        public string UIItemEditSendKeys21 = "{NumPad1}";
        
        /// <summary>
        /// Type 'Alt + {NumPad2}' in text box
        /// </summary>
        public string UIItemEditSendKeys22 = "{NumPad2}";
        
        /// <summary>
        /// Type 'Alt + {NumPad3}' in text box
        /// </summary>
        public string UIItemEditSendKeys23 = "{NumPad3}";
        
        /// <summary>
        /// Type 'Alt + {NumPad4}' in text box
        /// </summary>
        public string UIItemEditSendKeys24 = "{NumPad4}";
        
        /// <summary>
        /// Type 'Alt + {NumPad6}' in text box
        /// </summary>
        public string UIItemEditSendKeys25 = "{NumPad6}";
        
        /// <summary>
        /// Type 'Alt + {NumPad5}' in text box
        /// </summary>
        public string UIItemEditSendKeys26 = "{NumPad5}";
        
        /// <summary>
        /// Type 'Alt + {NumPad4}' in text box
        /// </summary>
        public string UIItemEditSendKeys27 = "{NumPad4}";
        
        /// <summary>
        /// Type 'Alt + {NumPad1}' in text box
        /// </summary>
        public string UIItemEditSendKeys28 = "{NumPad1}";
        
        /// <summary>
        /// Type 'Alt + {NumPad1}' in text box
        /// </summary>
        public string UIItemEditSendKeys29 = "{NumPad1}";
        
        /// <summary>
        /// Type 'Alt + {NumPad4}' in text box
        /// </summary>
        public string UIItemEditSendKeys30 = "{NumPad4}";
        
        /// <summary>
        /// Type 'Alt + {NumPad8}' in text box
        /// </summary>
        public string UIItemEditSendKeys31 = "{NumPad8}";
        
        /// <summary>
        /// Type 'Alt + {NumPad5}' in text box
        /// </summary>
        public string UIItemEditSendKeys32 = "{NumPad5}";
        
        /// <summary>
        /// Type 'Alt + {NumPad1}' in text box
        /// </summary>
        public string UIItemEditSendKeys33 = "{NumPad1}";
        
        /// <summary>
        /// Type 'Alt + {NumPad3}' in text box
        /// </summary>
        public string UIItemEditSendKeys34 = "{NumPad3}";
        
        /// <summary>
        /// Type 'Alt + {NumPad6}' in text box
        /// </summary>
        public string UIItemEditSendKeys35 = "{NumPad6}";
        
        /// <summary>
        /// Type 'Alt + {NumPad9}' in text box
        /// </summary>
        public string UIItemEditSendKeys36 = "{NumPad9}";
        
        /// <summary>
        /// Type 'Alt + {NumPad7}' in text box
        /// </summary>
        public string UIItemEditSendKeys37 = "{NumPad7}";
        
        /// <summary>
        /// Type 'Alt + {NumPad1}' in text box
        /// </summary>
        public string UIItemEditSendKeys38 = "{NumPad1}";
        
        /// <summary>
        /// Type 'Alt + {NumPad4}' in text box
        /// </summary>
        public string UIItemEditSendKeys39 = "{NumPad4}";
        
        /// <summary>
        /// Type 'Alt + {NumPad5}' in text box
        /// </summary>
        public string UIItemEditSendKeys40 = "{NumPad5}";
        
        /// <summary>
        /// Type 'Alt + {NumPad8}' in text box
        /// </summary>
        public string UIItemEditSendKeys41 = "{NumPad8}";
        
        /// <summary>
        /// Type 'Alt + {NumPad7}' in text box
        /// </summary>
        public string UIItemEditSendKeys42 = "{NumPad7}";
        
        /// <summary>
        /// Type 'Alt + {NumPad1}' in text box
        /// </summary>
        public string UIItemEditSendKeys43 = "{NumPad1}";
        
        /// <summary>
        /// Type 'Alt + {NumPad1}' in text box
        /// </summary>
        public string UIItemEditSendKeys44 = "{NumPad1}";
        
        /// <summary>
        /// Type 'Alt + {NumPad1}' in text box
        /// </summary>
        public string UIItemEditSendKeys45 = "{NumPad1}";
        
        /// <summary>
        /// Type 'Alt + {NumPad1}' in text box
        /// </summary>
        public string UIItemEditSendKeys46 = "{NumPad1}";
        
        /// <summary>
        /// Type 'Alt + {NumPad1}' in text box
        /// </summary>
        public string UIItemEditSendKeys47 = "{NumPad1}";
        
        /// <summary>
        /// Type 'Alt + {NumPad2}' in text box
        /// </summary>
        public string UIItemEditSendKeys48 = "{NumPad2}";
        
        /// <summary>
        /// Type 'Alt + {NumPad2}' in text box
        /// </summary>
        public string UIItemEditSendKeys49 = "{NumPad2}";
        
        /// <summary>
        /// Type 'Alt + {NumPad5}' in text box
        /// </summary>
        public string UIItemEditSendKeys50 = "{NumPad5}";
        
        /// <summary>
        /// Type 'Alt + {NumPad4}' in text box
        /// </summary>
        public string UIItemEditSendKeys51 = "{NumPad4}";
        
        /// <summary>
        /// Type 'Alt + {NumPad8}' in text box
        /// </summary>
        public string UIItemEditSendKeys52 = "{NumPad8}";
        
        /// <summary>
        /// Type 'Alt + {NumPad1}' in text box
        /// </summary>
        public string UIItemEditSendKeys53 = "{NumPad1}";
        
        /// <summary>
        /// Type 'Alt + {NumPad4}' in text box
        /// </summary>
        public string UIItemEditSendKeys54 = "{NumPad4}";
        
        /// <summary>
        /// Type 'Alt + {NumPad5}' in text box
        /// </summary>
        public string UIItemEditSendKeys55 = "{NumPad5}";
        
        /// <summary>
        /// Type 'Alt + {NumPad6}' in text box
        /// </summary>
        public string UIItemEditSendKeys56 = "{NumPad6}";
        
        /// <summary>
        /// Type 'Alt + {NumPad3}' in text box
        /// </summary>
        public string UIItemEditSendKeys57 = "{NumPad3}";
        
        /// <summary>
        /// Type 'Alt + {NumPad2}' in text box
        /// </summary>
        public string UIItemEditSendKeys58 = "{NumPad2}";
        
        /// <summary>
        /// Type 'Alt + {NumPad1}' in text box
        /// </summary>
        public string UIItemEditSendKeys59 = "{NumPad1}";
        
        /// <summary>
        /// Type 'Alt + {NumPad4}' in text box
        /// </summary>
        public string UIItemEditSendKeys60 = "{NumPad4}";
        
        /// <summary>
        /// Type 'Alt + {NumPad5}' in text box
        /// </summary>
        public string UIItemEditSendKeys61 = "{NumPad5}";
        
        /// <summary>
        /// Type 'Alt + {NumPad2}' in text box
        /// </summary>
        public string UIItemEditSendKeys62 = "{NumPad2}";
        
        /// <summary>
        /// Type 'Alt + {NumPad0}' in text box
        /// </summary>
        public string UIItemEditSendKeys63 = "{NumPad0}";
        
        /// <summary>
        /// Type 'Alt + {NumPad1}' in text box
        /// </summary>
        public string UIItemEditSendKeys64 = "{NumPad1}";
        
        /// <summary>
        /// Type 'Alt + {NumPad4}' in text box
        /// </summary>
        public string UIItemEditSendKeys65 = "{NumPad4}";
        
        /// <summary>
        /// Type 'Alt + {NumPad5}' in text box
        /// </summary>
        public string UIItemEditSendKeys66 = "{NumPad5}";
        
        /// <summary>
        /// Type 'Alt + {NumPad9}' in text box
        /// </summary>
        public string UIItemEditSendKeys67 = "{NumPad9}";
        
        /// <summary>
        /// Type 'Alt + {NumPad8}' in text box
        /// </summary>
        public string UIItemEditSendKeys68 = "{NumPad8}";
        
        /// <summary>
        /// Type 'Alt + {NumPad7}' in text box
        /// </summary>
        public string UIItemEditSendKeys69 = "{NumPad7}";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIUntitledNotepadWindow : WinWindow
    {
        
        public UIUntitledNotepadWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Untitled - Notepad";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Notepad";
            this.WindowTitles.Add("Untitled - Notepad");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "15";
            this.WindowTitles.Add("Untitled - Notepad");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("Untitled - Notepad");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
}
