// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Lots_of_Test_cases
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;


    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {

        /// <summary>
        /// TestAsciiValue32 - Use 'TestAsciiValue32Params' to pass parameters into this method.
        /// </summary>
        public void TestAsciiValue32()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue32Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue32Params TestAsciiValue32Params
        {
            get
            {
                if ((this.mTestAsciiValue32Params == null))
                {
                    this.mTestAsciiValue32Params = new TestAsciiValue32Params();
                }
                return this.mTestAsciiValue32Params;
            }
        }
        #endregion


        public void TestAsciiValue33()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue32Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue33Params TestAsciiValue33Params
        {
            get
            {
                if ((this.mTestAsciiValue33Params == null))
                {
                    this.mTestAsciiValue33Params = new TestAsciiValue33Params();
                }
                return this.mTestAsciiValue33Params;
            }
        }
        #endregion

        public void TestAsciiValue34()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue34Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue34Params TestAsciiValue34Params
        {
            get
            {
                if ((this.mTestAsciiValue34Params == null))
                {
                    this.mTestAsciiValue34Params = new TestAsciiValue34Params();
                }
                return this.mTestAsciiValue34Params;
            }
        }
        #endregion


        public void TestAsciiValue35()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue35Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue35Params TestAsciiValue35Params
        {
            get
            {
                if ((this.mTestAsciiValue35Params == null))
                {
                    this.mTestAsciiValue35Params = new TestAsciiValue35Params();
                }
                return this.mTestAsciiValue35Params;
            }
        }
        #endregion


        public void TestAsciiValue36()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue35Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue36Params TestAsciiValue36Params
        {
            get
            {
                if ((this.mTestAsciiValue36Params == null))
                {
                    this.mTestAsciiValue36Params = new TestAsciiValue36Params();
                }
                return this.mTestAsciiValue36Params;
            }
        }
        #endregion

        public void TestAsciiValue37()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue37Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue37Params TestAsciiValue37Params
        {
            get
            {
                if ((this.mTestAsciiValue37Params == null))
                {
                    this.mTestAsciiValue37Params = new TestAsciiValue37Params();
                }
                return this.mTestAsciiValue37Params;
            }
        }
        #endregion

        /// <summary>
        /// TestAsciiValue37 - Use 'TestAsciiValue37Params' to pass parameters into this method.
        /// </summary>
        public void TestAsciiValue38()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue38Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue38Params TestAsciiValue38Params
        {
            get
            {
                if ((this.mTestAsciiValue38Params == null))
                {
                    this.mTestAsciiValue38Params = new TestAsciiValue38Params();
                }
                return this.mTestAsciiValue38Params;
            }
        }
        #endregion

        /// <summary>
        /// TestAsciiValue38 - Use 'TestAsciiValue38Params' to pass parameters into this method.
        /// </summary>
        public void TestAsciiValue39()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue39Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue39Params TestAsciiValue39Params
        {
            get
            {
                if ((this.mTestAsciiValue39Params == null))
                {
                    this.mTestAsciiValue39Params = new TestAsciiValue39Params();
                }
                return this.mTestAsciiValue39Params;
            }
        }
        #endregion

        /// <summary>
        /// TestAsciiValue39 - Use 'TestAsciiValue39Params' to pass parameters into this method.
        /// </summary>
        public void TestAsciiValue40()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue40Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue40Params TestAsciiValue40Params
        {
            get
            {
                if ((this.mTestAsciiValue40Params == null))
                {
                    this.mTestAsciiValue40Params = new TestAsciiValue40Params();
                }
                return this.mTestAsciiValue40Params;
            }
        }
        #endregion

        /// <summary>
        /// TestAsciiValue40 - Use 'TestAsciiValue40Params' to pass parameters into this method.
        /// </summary>
        public void TestAsciiValue41()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue41Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue41Params TestAsciiValue41Params
        {
            get
            {
                if ((this.mTestAsciiValue41Params == null))
                {
                    this.mTestAsciiValue41Params = new TestAsciiValue41Params();
                }
                return this.mTestAsciiValue41Params;
            }
        }
        #endregion

        /// <summary>
        /// TestAsciiValue41 - Use 'TestAsciiValue41Params' to pass parameters into this method.
        /// </summary>
        public void TestAsciiValue42()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue42Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue42Params TestAsciiValue42Params
        {
            get
            {
                if ((this.mTestAsciiValue42Params == null))
                {
                    this.mTestAsciiValue42Params = new TestAsciiValue42Params();
                }
                return this.mTestAsciiValue42Params;
            }
        }
        #endregion

        /// <summary>
        /// TestAsciiValue42 - Use 'TestAsciiValue42Params' to pass parameters into this method.
        /// </summary>
        public void TestAsciiValue43()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue43Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue43Params TestAsciiValue43Params
        {
            get
            {
                if ((this.mTestAsciiValue43Params == null))
                {
                    this.mTestAsciiValue43Params = new TestAsciiValue43Params();
                }
                return this.mTestAsciiValue43Params;
            }
        }
        #endregion

        /// <summary>
        /// TestAsciiValue43 - Use 'TestAsciiValue43Params' to pass parameters into this method.
        /// </summary>
        public void TestAsciiValue44()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue44Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue44Params TestAsciiValue44Params
        {
            get
            {
                if ((this.mTestAsciiValue44Params == null))
                {
                    this.mTestAsciiValue44Params = new TestAsciiValue44Params();
                }
                return this.mTestAsciiValue44Params;
            }
        }
        #endregion

        /// <summary>
        /// TestAsciiValue44 - Use 'TestAsciiValue44Params' to pass parameters into this method.
        /// </summary>
        public void TestAsciiValue45()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue45Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue45Params TestAsciiValue45Params
        {
            get
            {
                if ((this.mTestAsciiValue45Params == null))
                {
                    this.mTestAsciiValue45Params = new TestAsciiValue45Params();
                }
                return this.mTestAsciiValue45Params;
            }
        }
        #endregion

        /// <summary>
        /// TestAsciiValue45 - Use 'TestAsciiValue45Params' to pass parameters into this method.
        /// </summary>
        public void TestAsciiValue46()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue46Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue46Params TestAsciiValue46Params
        {
            get
            {
                if ((this.mTestAsciiValue46Params == null))
                {
                    this.mTestAsciiValue46Params = new TestAsciiValue46Params();
                }
                return this.mTestAsciiValue46Params;
            }
        }
        #endregion

        /// <summary>
        /// TestAsciiValue46 - Use 'TestAsciiValue46Params' to pass parameters into this method.
        /// </summary>
        public void TestAsciiValue47()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue47Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue47Params TestAsciiValue47Params
        {
            get
            {
                if ((this.mTestAsciiValue47Params == null))
                {
                    this.mTestAsciiValue47Params = new TestAsciiValue47Params();
                }
                return this.mTestAsciiValue47Params;
            }
        }
        #endregion

        /// <summary>
        /// TestAsciiValue47 - Use 'TestAsciiValue47Params' to pass parameters into this method.
        /// </summary>
        public void TestAsciiValue48()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue48Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue48Params TestAsciiValue48Params
        {
            get
            {
                if ((this.mTestAsciiValue48Params == null))
                {
                    this.mTestAsciiValue48Params = new TestAsciiValue48Params();
                }
                return this.mTestAsciiValue48Params;
            }
        }
        #endregion

        /// <summary>
        /// TestAsciiValue48 - Use 'TestAsciiValue48Params' to pass parameters into this method.
        /// </summary>
        public void TestAsciiValue49()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue49Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue49Params TestAsciiValue49Params
        {
            get
            {
                if ((this.mTestAsciiValue49Params == null))
                {
                    this.mTestAsciiValue49Params = new TestAsciiValue49Params();
                }
                return this.mTestAsciiValue49Params;
            }
        }
        #endregion

        /// <summary>
        /// TestAsciiValue49 - Use 'TestAsciiValue49Params' to pass parameters into this method.
        /// </summary>
        public void TestAsciiValue50()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue50Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue50Params TestAsciiValue50Params
        {
            get
            {
                if ((this.mTestAsciiValue50Params == null))
                {
                    this.mTestAsciiValue50Params = new TestAsciiValue50Params();
                }
                return this.mTestAsciiValue50Params;
            }
        }
        #endregion

        /// <summary>
        /// TestAsciiValue50 - Use 'TestAsciiValue50Params' to pass parameters into this method.
        /// </summary>
        public void TestAsciiValue51()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue51Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue51Params TestAsciiValue51Params
        {
            get
            {
                if ((this.mTestAsciiValue51Params == null))
                {
                    this.mTestAsciiValue51Params = new TestAsciiValue51Params();
                }
                return this.mTestAsciiValue51Params;
            }
        }
        #endregion

        /// <summary>
        /// TestAsciiValue51 - Use 'TestAsciiValue51Params' to pass parameters into this method.
        /// </summary>
        public void TestAsciiValue52()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue52Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue52Params TestAsciiValue52Params
        {
            get
            {
                if ((this.mTestAsciiValue52Params == null))
                {
                    this.mTestAsciiValue52Params = new TestAsciiValue52Params();
                }
                return this.mTestAsciiValue52Params;
            }
        }
        #endregion

        /// <summary>
        /// TestAsciiValue52 - Use 'TestAsciiValue52Params' to pass parameters into this method.
        /// </summary>
        public void TestAsciiValue53()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue53Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue53Params TestAsciiValue53Params
        {
            get
            {
                if ((this.mTestAsciiValue53Params == null))
                {
                    this.mTestAsciiValue53Params = new TestAsciiValue53Params();
                }
                return this.mTestAsciiValue53Params;
            }
        }
        #endregion

        /// <summary>
        /// TestAsciiValue53 - Use 'TestAsciiValue53Params' to pass parameters into this method.
        /// </summary>
        public void TestAsciiValue54()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue54Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue54Params TestAsciiValue54Params
        {
            get
            {
                if ((this.mTestAsciiValue54Params == null))
                {
                    this.mTestAsciiValue54Params = new TestAsciiValue54Params();
                }
                return this.mTestAsciiValue54Params;
            }
        }
        #endregion

        /// <summary>
        /// TestAsciiValue54 - Use 'TestAsciiValue54Params' to pass parameters into this method.
        /// </summary>
        public void TestAsciiValue55()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue55Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue55Params TestAsciiValue55Params
        {
            get
            {
                if ((this.mTestAsciiValue55Params == null))
                {
                    this.mTestAsciiValue55Params = new TestAsciiValue55Params();
                }
                return this.mTestAsciiValue55Params;
            }
        }
        #endregion

        /// <summary>
        /// TestAsciiValue55 - Use 'TestAsciiValue55Params' to pass parameters into this method.
        /// </summary>
        public void TestAsciiValue56()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue56Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue56Params TestAsciiValue56Params
        {
            get
            {
                if ((this.mTestAsciiValue56Params == null))
                {
                    this.mTestAsciiValue56Params = new TestAsciiValue56Params();
                }
                return this.mTestAsciiValue56Params;
            }
        }
        #endregion

        /// <summary>
        /// TestAsciiValue56 - Use 'TestAsciiValue56Params' to pass parameters into this method.
        /// </summary>
        public void TestAsciiValue57()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue57Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue57Params TestAsciiValue57Params
        {
            get
            {
                if ((this.mTestAsciiValue57Params == null))
                {
                    this.mTestAsciiValue57Params = new TestAsciiValue57Params();
                }
                return this.mTestAsciiValue57Params;
            }
        }
        #endregion

        /// <summary>
        /// TestAsciiValue57 - Use 'TestAsciiValue57Params' to pass parameters into this method.
        /// </summary>
        public void TestAsciiValue58()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue58Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue58Params TestAsciiValue58Params
        {
            get
            {
                if ((this.mTestAsciiValue58Params == null))
                {
                    this.mTestAsciiValue58Params = new TestAsciiValue58Params();
                }
                return this.mTestAsciiValue58Params;
            }
        }
        #endregion

        /// <summary>
        /// TestAsciiValue58 - Use 'TestAsciiValue58Params' to pass parameters into this method.
        /// </summary>
        public void TestAsciiValue59()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue59Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue59Params TestAsciiValue59Params
        {
            get
            {
                if ((this.mTestAsciiValue59Params == null))
                {
                    this.mTestAsciiValue59Params = new TestAsciiValue59Params();
                }
                return this.mTestAsciiValue59Params;
            }
        }
        #endregion

        /// <summary>
        /// TestAsciiValue59 - Use 'TestAsciiValue59Params' to pass parameters into this method.
        /// </summary>
        public void TestAsciiValue60()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue60Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue60Params TestAsciiValue60Params
        {
            get
            {
                if ((this.mTestAsciiValue60Params == null))
                {
                    this.mTestAsciiValue60Params = new TestAsciiValue60Params();
                }
                return this.mTestAsciiValue60Params;
            }
        }
        #endregion

        /// <summary>
        /// TestAsciiValue60 - Use 'TestAsciiValue60Params' to pass parameters into this method.
        /// </summary>
        public void TestAsciiValue61()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue61Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue61Params TestAsciiValue61Params
        {
            get
            {
                if ((this.mTestAsciiValue61Params == null))
                {
                    this.mTestAsciiValue61Params = new TestAsciiValue61Params();
                }
                return this.mTestAsciiValue61Params;
            }
        }
        #endregion

        /// <summary>
        /// TestAsciiValue61 - Use 'TestAsciiValue61Params' to pass parameters into this method.
        /// </summary>
        public void TestAsciiValue62()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue62Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue62Params TestAsciiValue62Params
        {
            get
            {
                if ((this.mTestAsciiValue62Params == null))
                {
                    this.mTestAsciiValue62Params = new TestAsciiValue62Params();
                }
                return this.mTestAsciiValue62Params;
            }
        }
        #endregion

        /// <summary>
        /// TestAsciiValue62 - Use 'TestAsciiValue62Params' to pass parameters into this method.
        /// </summary>
        public void TestAsciiValue63()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue63Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue63Params TestAsciiValue63Params
        {
            get
            {
                if ((this.mTestAsciiValue63Params == null))
                {
                    this.mTestAsciiValue63Params = new TestAsciiValue63Params();
                }
                return this.mTestAsciiValue63Params;
            }
        }
        #endregion

        /// <summary>
        /// TestAsciiValue63 - Use 'TestAsciiValue63Params' to pass parameters into this method.
        /// </summary>
        public void TestAsciiValue64()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue64Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue64Params TestAsciiValue64Params
        {
            get
            {
                if ((this.mTestAsciiValue64Params == null))
                {
                    this.mTestAsciiValue64Params = new TestAsciiValue64Params();
                }
                return this.mTestAsciiValue64Params;
            }
        }
        #endregion

        /// <summary>
        /// TestAsciiValue64 - Use 'TestAsciiValue64Params' to pass parameters into this method.
        /// </summary>
        public void TestAsciiValue65()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue65Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue65Params TestAsciiValue65Params
        {
            get
            {
                if ((this.mTestAsciiValue65Params == null))
                {
                    this.mTestAsciiValue65Params = new TestAsciiValue65Params();
                }
                return this.mTestAsciiValue65Params;
            }
        }
        #endregion

        /// <summary>
        /// TestAsciiValue65 - Use 'TestAsciiValue65Params' to pass parameters into this method.
        /// </summary>
        public void TestAsciiValue66()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue66Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue66Params TestAsciiValue66Params
        {
            get
            {
                if ((this.mTestAsciiValue66Params == null))
                {
                    this.mTestAsciiValue66Params = new TestAsciiValue66Params();
                }
                return this.mTestAsciiValue66Params;
            }
        }
        #endregion

        /// <summary>
        /// TestAsciiValue66 - Use 'TestAsciiValue66Params' to pass parameters into this method.
        /// </summary>
        public void TestAsciiValue67()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue67Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue67Params TestAsciiValue67Params
        {
            get
            {
                if ((this.mTestAsciiValue67Params == null))
                {
                    this.mTestAsciiValue67Params = new TestAsciiValue67Params();
                }
                return this.mTestAsciiValue67Params;
            }
        }
        #endregion

        /// <summary>
        /// TestAsciiValue67 - Use 'TestAsciiValue67Params' to pass parameters into this method.
        /// </summary>
        public void TestAsciiValue68()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue68Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue68Params TestAsciiValue68Params
        {
            get
            {
                if ((this.mTestAsciiValue68Params == null))
                {
                    this.mTestAsciiValue68Params = new TestAsciiValue68Params();
                }
                return this.mTestAsciiValue68Params;
            }
        }
        #endregion

        /// <summary>
        /// TestAsciiValue68 - Use 'TestAsciiValue68Params' to pass parameters into this method.
        /// </summary>
        public void TestAsciiValue69()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue69Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue69Params TestAsciiValue69Params
        {
            get
            {
                if ((this.mTestAsciiValue69Params == null))
                {
                    this.mTestAsciiValue69Params = new TestAsciiValue69Params();
                }
                return this.mTestAsciiValue69Params;
            }
        }
        #endregion

        /// <summary>
        /// TestAsciiValue69 - Use 'TestAsciiValue69Params' to pass parameters into this method.
        /// </summary>
        public void TestAsciiValue70()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue70Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue70Params TestAsciiValue70Params
        {
            get
            {
                if ((this.mTestAsciiValue70Params == null))
                {
                    this.mTestAsciiValue70Params = new TestAsciiValue70Params();
                }
                return this.mTestAsciiValue70Params;
            }
        }
        #endregion

        /// <summary>
        /// TestAsciiValue70 - Use 'TestAsciiValue70Params' to pass parameters into this method.
        /// </summary>
        public void TestAsciiValue71()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue71Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue71Params TestAsciiValue71Params
        {
            get
            {
                if ((this.mTestAsciiValue71Params == null))
                {
                    this.mTestAsciiValue71Params = new TestAsciiValue71Params();
                }
                return this.mTestAsciiValue71Params;
            }
        }
        #endregion

        /// <summary>
        /// TestAsciiValue71 - Use 'TestAsciiValue71Params' to pass parameters into this method.
        /// </summary>
        public void TestAsciiValue72()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue72Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue72Params TestAsciiValue72Params
        {
            get
            {
                if ((this.mTestAsciiValue72Params == null))
                {
                    this.mTestAsciiValue72Params = new TestAsciiValue72Params();
                }
                return this.mTestAsciiValue72Params;
            }
        }
        #endregion

        public void TestAsciiValue73()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue73Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue73Params TestAsciiValue73Params
        {
            get
            {
                if ((this.mTestAsciiValue73Params == null))
                {
                    this.mTestAsciiValue73Params = new TestAsciiValue73Params();
                }
                return this.mTestAsciiValue73Params;
            }
        }
        #endregion

        public void TestAsciiValue74()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue74Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue74Params TestAsciiValue74Params
        {
            get
            {
                if ((this.mTestAsciiValue74Params == null))
                {
                    this.mTestAsciiValue74Params = new TestAsciiValue74Params();
                }
                return this.mTestAsciiValue74Params;
            }
        }
        #endregion

        public void TestAsciiValue75()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue75Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue75Params TestAsciiValue75Params
        {
            get
            {
                if ((this.mTestAsciiValue75Params == null))
                {
                    this.mTestAsciiValue75Params = new TestAsciiValue75Params();
                }
                return this.mTestAsciiValue75Params;
            }
        }
        #endregion

        public void TestAsciiValue76()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue76Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue76Params TestAsciiValue76Params
        {
            get
            {
                if ((this.mTestAsciiValue76Params == null))
                {
                    this.mTestAsciiValue76Params = new TestAsciiValue76Params();
                }
                return this.mTestAsciiValue76Params;
            }
        }
        #endregion

        public void TestAsciiValue77()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue77Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue77Params TestAsciiValue77Params
        {
            get
            {
                if ((this.mTestAsciiValue77Params == null))
                {
                    this.mTestAsciiValue77Params = new TestAsciiValue77Params();
                }
                return this.mTestAsciiValue77Params;
            }
        }
        #endregion

        public void TestAsciiValue78()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue78Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue78Params TestAsciiValue78Params
        {
            get
            {
                if ((this.mTestAsciiValue78Params == null))
                {
                    this.mTestAsciiValue78Params = new TestAsciiValue78Params();
                }
                return this.mTestAsciiValue78Params;
            }
        }
        #endregion

        public void TestAsciiValue79()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue79Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue79Params TestAsciiValue79Params
        {
            get
            {
                if ((this.mTestAsciiValue79Params == null))
                {
                    this.mTestAsciiValue79Params = new TestAsciiValue79Params();
                }
                return this.mTestAsciiValue79Params;
            }
        }
        #endregion

        public void TestAsciiValue80()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue80Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue80Params TestAsciiValue80Params
        {
            get
            {
                if ((this.mTestAsciiValue80Params == null))
                {
                    this.mTestAsciiValue80Params = new TestAsciiValue80Params();
                }
                return this.mTestAsciiValue80Params;
            }
        }
        #endregion

        public void TestAsciiValue81()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue81Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue81Params TestAsciiValue81Params
        {
            get
            {
                if ((this.mTestAsciiValue81Params == null))
                {
                    this.mTestAsciiValue81Params = new TestAsciiValue81Params();
                }
                return this.mTestAsciiValue81Params;
            }
        }
        #endregion

        public void TestAsciiValue82()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue82Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue82Params TestAsciiValue82Params
        {
            get
            {
                if ((this.mTestAsciiValue82Params == null))
                {
                    this.mTestAsciiValue82Params = new TestAsciiValue82Params();
                }
                return this.mTestAsciiValue82Params;
            }
        }
        #endregion

        public void TestAsciiValue83()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue83Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue83Params TestAsciiValue83Params
        {
            get
            {
                if ((this.mTestAsciiValue83Params == null))
                {
                    this.mTestAsciiValue83Params = new TestAsciiValue83Params();
                }
                return this.mTestAsciiValue83Params;
            }
        }
        #endregion

        public void TestAsciiValue84()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue84Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue84Params TestAsciiValue84Params
        {
            get
            {
                if ((this.mTestAsciiValue84Params == null))
                {
                    this.mTestAsciiValue84Params = new TestAsciiValue84Params();
                }
                return this.mTestAsciiValue84Params;
            }
        }
        #endregion

        public void TestAsciiValue85()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue85Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue85Params TestAsciiValue85Params
        {
            get
            {
                if ((this.mTestAsciiValue85Params == null))
                {
                    this.mTestAsciiValue85Params = new TestAsciiValue85Params();
                }
                return this.mTestAsciiValue85Params;
            }
        }
        #endregion

        public void TestAsciiValue86()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue86Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue86Params TestAsciiValue86Params
        {
            get
            {
                if ((this.mTestAsciiValue86Params == null))
                {
                    this.mTestAsciiValue86Params = new TestAsciiValue86Params();
                }
                return this.mTestAsciiValue86Params;
            }
        }
        #endregion

        public void TestAsciiValue87()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue87Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue87Params TestAsciiValue87Params
        {
            get
            {
                if ((this.mTestAsciiValue87Params == null))
                {
                    this.mTestAsciiValue87Params = new TestAsciiValue87Params();
                }
                return this.mTestAsciiValue87Params;
            }
        }
        #endregion

        public void TestAsciiValue88()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue88Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue88Params TestAsciiValue88Params
        {
            get
            {
                if ((this.mTestAsciiValue88Params == null))
                {
                    this.mTestAsciiValue88Params = new TestAsciiValue88Params();
                }
                return this.mTestAsciiValue88Params;
            }
        }
        #endregion

        public void TestAsciiValue89()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue89Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue89Params TestAsciiValue89Params
        {
            get
            {
                if ((this.mTestAsciiValue89Params == null))
                {
                    this.mTestAsciiValue89Params = new TestAsciiValue89Params();
                }
                return this.mTestAsciiValue89Params;
            }
        }
        #endregion

        public void TestAsciiValue90()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue90Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue90Params TestAsciiValue90Params
        {
            get
            {
                if ((this.mTestAsciiValue90Params == null))
                {
                    this.mTestAsciiValue90Params = new TestAsciiValue90Params();
                }
                return this.mTestAsciiValue90Params;
            }
        }
        #endregion

        public void TestAsciiValue91()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue91Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue91Params TestAsciiValue91Params
        {
            get
            {
                if ((this.mTestAsciiValue91Params == null))
                {
                    this.mTestAsciiValue91Params = new TestAsciiValue91Params();
                }
                return this.mTestAsciiValue91Params;
            }
        }
        #endregion

        public void TestAsciiValue92()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue92Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue92Params TestAsciiValue92Params
        {
            get
            {
                if ((this.mTestAsciiValue92Params == null))
                {
                    this.mTestAsciiValue92Params = new TestAsciiValue92Params();
                }
                return this.mTestAsciiValue92Params;
            }
        }
        #endregion

        public void TestAsciiValue93()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'hellohello world' in text box
            uIItemEdit.Text = this.TestAsciiValue93Params.UIItemEditText;
        }

        #region Properties
        public virtual TestAsciiValue93Params TestAsciiValue93Params
        {
            get
            {
                if ((this.mTestAsciiValue93Params == null))
                {
                    this.mTestAsciiValue93Params = new TestAsciiValue93Params();
                }
                return this.mTestAsciiValue93Params;
            }
        }
        #endregion


















        public UIUntitledNotepadWindow UIUntitledNotepadWindow
        {
            get
            {
                if ((this.mUIUntitledNotepadWindow == null))
                {
                    this.mUIUntitledNotepadWindow = new UIUntitledNotepadWindow();
                }
                return this.mUIUntitledNotepadWindow;
            }
        }
        

        #region Fields
        private TestAsciiValue32Params mTestAsciiValue32Params;
        private TestAsciiValue33Params mTestAsciiValue33Params;
        private TestAsciiValue34Params mTestAsciiValue34Params;
        private TestAsciiValue35Params mTestAsciiValue35Params;
        private TestAsciiValue36Params mTestAsciiValue36Params;
        private TestAsciiValue37Params mTestAsciiValue37Params;
        private TestAsciiValue38Params mTestAsciiValue38Params;
        private TestAsciiValue39Params mTestAsciiValue39Params;
        private TestAsciiValue40Params mTestAsciiValue40Params;
        private TestAsciiValue41Params mTestAsciiValue41Params;
        private TestAsciiValue42Params mTestAsciiValue42Params;
        private TestAsciiValue43Params mTestAsciiValue43Params;
        private TestAsciiValue44Params mTestAsciiValue44Params;
        private TestAsciiValue45Params mTestAsciiValue45Params;
        private TestAsciiValue46Params mTestAsciiValue46Params;
        private TestAsciiValue47Params mTestAsciiValue47Params;
        private TestAsciiValue48Params mTestAsciiValue48Params;
        private TestAsciiValue49Params mTestAsciiValue49Params;
        private TestAsciiValue50Params mTestAsciiValue50Params;
        private TestAsciiValue51Params mTestAsciiValue51Params;
        private TestAsciiValue52Params mTestAsciiValue52Params;
        private TestAsciiValue53Params mTestAsciiValue53Params;
        private TestAsciiValue54Params mTestAsciiValue54Params;
        private TestAsciiValue55Params mTestAsciiValue55Params;
        private TestAsciiValue56Params mTestAsciiValue56Params;
        private TestAsciiValue57Params mTestAsciiValue57Params;
        private TestAsciiValue58Params mTestAsciiValue58Params;
        private TestAsciiValue59Params mTestAsciiValue59Params;
        private TestAsciiValue60Params mTestAsciiValue60Params;
        private TestAsciiValue61Params mTestAsciiValue61Params;
        private TestAsciiValue62Params mTestAsciiValue62Params;
        private TestAsciiValue63Params mTestAsciiValue63Params;
        private TestAsciiValue64Params mTestAsciiValue64Params;
        private TestAsciiValue65Params mTestAsciiValue65Params;
        private TestAsciiValue66Params mTestAsciiValue66Params;
        private TestAsciiValue67Params mTestAsciiValue67Params;
        private TestAsciiValue68Params mTestAsciiValue68Params;
        private TestAsciiValue69Params mTestAsciiValue69Params;
        private TestAsciiValue70Params mTestAsciiValue70Params;
        private TestAsciiValue71Params mTestAsciiValue71Params;
        private TestAsciiValue72Params mTestAsciiValue72Params;
        private TestAsciiValue73Params mTestAsciiValue73Params;
        private TestAsciiValue74Params mTestAsciiValue74Params;
        private TestAsciiValue75Params mTestAsciiValue75Params;
        private TestAsciiValue76Params mTestAsciiValue76Params;
        private TestAsciiValue77Params mTestAsciiValue77Params;
        private TestAsciiValue78Params mTestAsciiValue78Params;
        private TestAsciiValue79Params mTestAsciiValue79Params;
        private TestAsciiValue80Params mTestAsciiValue80Params;
        private TestAsciiValue81Params mTestAsciiValue81Params;
        private TestAsciiValue82Params mTestAsciiValue82Params;
        private TestAsciiValue83Params mTestAsciiValue83Params;
        private TestAsciiValue84Params mTestAsciiValue84Params;
        private TestAsciiValue85Params mTestAsciiValue85Params;
        private TestAsciiValue86Params mTestAsciiValue86Params;
        private TestAsciiValue87Params mTestAsciiValue87Params;
        private TestAsciiValue88Params mTestAsciiValue88Params;
        private TestAsciiValue89Params mTestAsciiValue89Params;
        private TestAsciiValue90Params mTestAsciiValue90Params;
        private TestAsciiValue91Params mTestAsciiValue91Params;
        private TestAsciiValue92Params mTestAsciiValue92Params;
        private TestAsciiValue93Params mTestAsciiValue93Params;

        private UIUntitledNotepadWindow mUIUntitledNotepadWindow;
        #endregion
    }

    /// <summary>
    /// Parameters to be passed into 'TestAsciiValue32'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class TestAsciiValue32Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(32, 32);
                ret += c;
            }
            return "These should be spaces \n" + ret + "\nIt should be blank until now";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue48Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(48, 48);
                ret += c;
            }
            return "These should be 0 --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue33Params
    {

        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(33, 33);
                ret += c;
            }
            return "These should be ! --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue34Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(34, 34);
                ret += c;
            }
            return "These should be \" --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue35Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(35, 35);
                ret += c;
            }
            return "These should be # --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue36Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(36, 36);
                ret += c;
            }
            return "These should be $ --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue37Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(37, 37);
                ret += c;
            }
            return "These should be % --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue38Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(38, 38);
                ret += c;
            }
            return "These should be & --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue39Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(39, 39);
                ret += c;
            }
            return "These should be ' --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue40Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(40, 40);
                ret += c;
            }
            return "These should be ( --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue41Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(41, 41);
                ret += c;
            }
            return "These should be ) --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue42Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(42, 42);
                ret += c;
            }
            return "These should be * --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue43Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(43, 43);
                ret += c;
            }
            return "These should be + --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue44Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(44, 44);
                ret += c;
            }
            return "These should be , --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue45Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(45, 45);
                ret += c;
            }
            return "These should be - --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue46Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(46, 46);
                ret += c;
            }
            return "These should be . --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue47Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(47, 47);
                ret += c;
            }
            return "These should be / --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue49Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(49, 49);
                ret += c;
            }
            return "These should be 1 --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue50Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(50, 50);
                ret += c;
            }
            return "These should be 2 --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue51Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(51, 51);
                ret += c;
            }
            return "These should be 3 --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue52Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(52, 52);
                ret += c;
            }
            return "These should be 4 --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue53Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(53, 53);
                ret += c;
            }
            return "These should be 5 --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue54Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(54, 54);
                ret += c;
            }
            return "These should be 6 --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue55Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(55, 55);
                ret += c;
            }
            return "These should be 7 --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue56Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(56, 56);
                ret += c;
            }
            return "These should be 8 --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue57Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(57, 57);
                ret += c;
            }
            return "These should be 9 --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue58Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(58, 58);
                ret += c;
            }
            return "These should be : --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue59Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(59, 59);
                ret += c;
            }
            return "These should be ; --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue60Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(60, 60);
                ret += c;
            }
            return "These should be < --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue61Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(61, 61);
                ret += c;
            }
            return "These should be = --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue62Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(62, 62);
                ret += c;
            }
            return "These should be > --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue63Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(63, 63);
                ret += c;
            }
            return "These should be ? --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue64Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(64, 64);
                ret += c;
            }
            return "These should be @ --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue65Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(65, 65);
                ret += c;
            }
            return "These should be A --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue66Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(66, 66);
                ret += c;
            }
            return "These should be B --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue67Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(67, 67);
                ret += c;
            }
            return "These should be C --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue68Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(68, 68);
                ret += c;
            }
            return "These should be D --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue69Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(69, 69);
                ret += c;
            }
            return "These should be E --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue70Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(70, 70);
                ret += c;
            }
            return "These should be F --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue71Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(71, 71);
                ret += c;
            }
            return "These should be G --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }
    public class TestAsciiValue72Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(72, 72);
                ret += c;
            }
            return "These should be H --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }

    public class TestAsciiValue73Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(73, 73);
                ret += c;
            }
            return "These should be I --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }


    public class TestAsciiValue74Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(74, 74);
                ret += c;
            }
            return "These should be J --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }

    public class TestAsciiValue75Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(75, 75);
                ret += c;
            }
            return "These should be K --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }

    public class TestAsciiValue76Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(76, 76);
                ret += c;
            }
            return "These should be L --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }

    public class TestAsciiValue77Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(77, 77);
                ret += c;
            }
            return "These should be M --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }

    public class TestAsciiValue78Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(78, 78);
                ret += c;
            }
            return "These should be N --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }

    public class TestAsciiValue79Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(79, 79);
                ret += c;
            }
            return "These should be O --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }

    public class TestAsciiValue80Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(80, 80);
                ret += c;
            }
            return "These should be P --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }

    public class TestAsciiValue81Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(81, 81);
                ret += c;
            }
            return "These should be Q --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }

    public class TestAsciiValue82Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(82, 82);
                ret += c;
            }
            return "These should be R --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }

    public class TestAsciiValue83Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(83, 83);
                ret += c;
            }
            return "These should be S --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }

    public class TestAsciiValue84Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(84, 84);
                ret += c;
            }
            return "These should be T --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }

    public class TestAsciiValue85Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(85, 85);
                ret += c;
            }
            return "These should be U --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }

    public class TestAsciiValue86Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(86, 86);
                ret += c;
            }
            return "These should be V --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }

    public class TestAsciiValue87Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(87, 87);
                ret += c;
            }
            return "These should be W --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }

    public class TestAsciiValue88Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(88, 88);
                ret += c;
            }
            return "These should be X --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }

    public class TestAsciiValue89Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(89, 89);
                ret += c;
            }
            return "These should be Y --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }

    public class TestAsciiValue90Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(90, 90);
                ret += c;
            }
            return "These should be Z --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }

    public class TestAsciiValue91Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(91, 91);
                ret += c;
            }
            return "These should be [ --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }

    public class TestAsciiValue92Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(92, 92);
                ret += c;
            }
            return "These should be \\ --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }

    public class TestAsciiValue93Params
    {
        public static String GenAsciiChar()
        {
            string ret = "";
            Random rnd = new Random();
            int size = rnd.Next(5, 25);
            for (int i = 0; i < size; i++)
            {
                char c = (char)rnd.Next(93, 93);
                ret += c;
            }
            return "These should be ] --> " + ret + "\n";
        }
        #region Fields
        /// <summary>
        /// Type 'some char character' in text box
        /// </summary>
        public string UIItemEditText = GenAsciiChar();
        #endregion
    }





























    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIUntitledNotepadWindow : WinWindow
    {

        public UIUntitledNotepadWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Untitled - Notepad";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Notepad";
            this.WindowTitles.Add("Untitled - Notepad");
            #endregion
        }

        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion

        #region Fields
        private UIItemWindow mUIItemWindow;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemWindow : WinWindow
    {

        public UIItemWindow(UITestControl searchLimitContainer) :
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "15";
            this.WindowTitles.Add("Untitled - Notepad");
            #endregion
        }

        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("Untitled - Notepad");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion

        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
}