// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TestWithShiftKey
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// ShiftHelloWorld - Use 'ShiftHelloWorldParams' to pass parameters into this method.
        /// </summary>
        public void ShiftHelloWorld()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type 'HELLO WORLD' in text box
            for (int i = 0; i < 10; i++)
            {
                uIItemEdit.Text = this.ShiftHelloWorldParams.UIItemEditText;
            }
        }
        
        /// <summary>
        /// Shift1to0 - Use 'Shift1to0Params' to pass parameters into this method.
        /// </summary>
        public void Shift1to0()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIUntitledNotepadWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Type '!@#$%^&*()_+' in text box
            for (int i = 0; i < 10; i++)
            {
                uIItemEdit.Text = this.Shift1to0Params.UIItemEditText;
            }
         }
        
        #region Properties
        public virtual ShiftHelloWorldParams ShiftHelloWorldParams
        {
            get
            {
                if ((this.mShiftHelloWorldParams == null))
                {
                    this.mShiftHelloWorldParams = new ShiftHelloWorldParams();
                }
                return this.mShiftHelloWorldParams;
            }
        }
        
        public virtual Shift1to0Params Shift1to0Params
        {
            get
            {
                if ((this.mShift1to0Params == null))
                {
                    this.mShift1to0Params = new Shift1to0Params();
                }
                return this.mShift1to0Params;
            }
        }
        
        public UIUntitledNotepadWindow UIUntitledNotepadWindow
        {
            get
            {
                if ((this.mUIUntitledNotepadWindow == null))
                {
                    this.mUIUntitledNotepadWindow = new UIUntitledNotepadWindow();
                }
                return this.mUIUntitledNotepadWindow;
            }
        }
        #endregion
        
        #region Fields
        private ShiftHelloWorldParams mShiftHelloWorldParams;
        
        private Shift1to0Params mShift1to0Params;
        
        private UIUntitledNotepadWindow mUIUntitledNotepadWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'ShiftHelloWorld'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class ShiftHelloWorldParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'HELLO WORLD' in text box
        /// </summary>
        public string UIItemEditText = "HELLO WORLD";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Shift1to0'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class Shift1to0Params
    {
        
        #region Fields
        /// <summary>
        /// Type '!@#$%^&*()_+' in text box
        /// </summary>
        public string UIItemEditText = "!@#$%^&*()_+";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIUntitledNotepadWindow : WinWindow
    {
        
        public UIUntitledNotepadWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Untitled - Notepad";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Notepad";
            this.WindowTitles.Add("Untitled - Notepad");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "15";
            this.WindowTitles.Add("Untitled - Notepad");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("Untitled - Notepad");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
}
